export const projectsList = [
  {
    title: "Elemental",
    description: `A web app that showcases reusable UI components with interactive demos and code snippets for developers. Built with React and Tailwind CSS, Elemental highlights real-world UI solutions with clean, reusable code. Explore components in action, review their implementation, and seamlessly integrate them into your own projects.`,
    skills: [ "Tailwind CSS","Typescript", "Next.js"],
    imagePath: "/projects/elemental1.png",
    githubLink: "https://github.com/kevincas01/elemental",
    siteLink: "https://elemental-ui.vercel.app/",
    features: [
      "Explore fully interactive UI components in action",
      "Gain access to clean, reusable code examples for every component",
      "Discover a curated collection of essential UI elements, from buttons to cards, designed for seamless integration",
      "Easily copy and integrate component code into your own projects",
    ],
    media: [
      {
        title: "Home Page",
        src: "/projects/Elemental/home.png",
        alt: "Home Page",
        fileType: "image",
      },
      {
        title: "All Components Page",
        src: "/projects/Elemental/components.png",
        alt: "All Components Page",
        fileType: "image",
      },
      {
        title: "Component Page - Card Example",
        src: "/projects/Elemental/cardComponents.png",
        alt: "Card Components Page",
        fileType: "image",
      },
      {
        title: "Component Page - Card Code Example",
        src: "/projects/Elemental/cardComponentsCode.png",
        alt: "Card Components Page - Code",
        fileType: "image",
      },
    ],
  },
  {
    title: "Vibify - Spotify social media app",
    description: `A full-stack web app that enhances your Spotify experience with personalized insights and social recommendations. Explore top artists, tracks, and recently played songs. The Recommendations Page lets you discover new music, share favorites, and seamlessly add them to your Spotify playlists.`,
    skills: ["Tailwind CSS","Typescript", "Next.js", "NextAuth", "Spotify API"],
    imagePath: "/projects/vibify1.png",
    githubLink: "https://github.com/kevincas01/Vibify",
    features: [
      "Explore top artists and tracks and filter by time period and number of items",
      "Discover music through recommendations from other users",
      "Share and recommend tracks, artists, albums, or playlists to the app",
      ">Seamlessly add recommendations to your Spotify playlists",
      "Handle music playback control and play a track directly from the app",
    ],
    media: [
      {
        title: "Dashboard Page",
        src: "/projects/Vibify/dashboard.png",
        alt: "Dashboard",
        fileType: "image",
      },
      {
        title: "Recommendations Feed Page",
        src: "/projects/Vibify/feed.png",
        alt: "Recommendations Feed Page",
        fileType: "image",
      },
      {
        title: "Recommending Page",
        src: "/projects/Vibify/recommending.png",
        alt: "Recommending Page",
        fileType: "image",
      },
      {
        title: "Recommending Process",
        src: "/projects/Vibify/recommending.mp4",
        alt: "Recommending Process Video",
        fileType: "video",
      },
      {
        title: "Top Tracks Page",
        src: "/projects/Vibify/tracks.png",
        alt: "Top Tracks Page",
        fileType: "image",
      },
      {
        title: "Top Artists Page",
        src: "/projects/Vibify/artists.png",
        alt: "Top Artists Page",
        fileType: "image",
      },
      {
        title: "Playlists Page",
        src: "/projects/Vibify/playlists.png",
        alt: "Spotify Playlists Page",
        fileType: "image",
      },
    ],
  },
  {
    title: "AlgoLens",
    description: `A web app that helps to visualize how data structures and algorithms work, including pathfinding and sorting techniques. Watch as algorithms like Depth First Search, QuickSort, and MergeSort execute step by step. Designed for students and developers, AlgoLens provides an interactive way to explore and understand how algorithms work.`,
    skills: ["React", "Javascript", "CSS", "SVG"],
    imagePath: "/projects/algolens1.png",
    githubLink: "https://github.com/kevincas01/AlgoLens",
  },
  {
    title: "Unlimited",
    description: `A fully functional replica of the NYT Wordle and Connections games, enabling users to play unlimited games without the daily restriction. The application mirrors the core gameplay mechanics of the original games, offering users the same word puzzle challenges and variety, but with the added benefit of unlimited gameplay, making it accessible at any time.`,
    skills: ["React", "Javascript", "CSS"],
    imagePath: "/projects/unlimited1.png",
    githubLink: "https://github.com/kevincas01/gamecenter-single-player",
    siteLink: "https://gamecenter-single-player.vercel.app/",
  },
  {
    title: "Vidload",
    description: `A video streaming application that allows users to upload, edit, and view videos. To support these features, I built a Node.js API server that facilitates video and image uploads to an AWS S3 bucket, transfers media via AWS CloudFront for fast delivery, and stores user data securely in a PostgreSQL database.`,
    skills: ["AWS S3 & Cloudfront", "Typescript", "React", "JWT Authentication"],
    githubLink: "https://github.com/kevincas01/Video-Upload",
  },
  {
    title: "Spaceship Trainer",
    description: `Developed and designed a 3D first person shooting game built with the Three.js 3D computer graphics framework.`,
    skills: ["Three.js", "HTML", "Javascript", "CSS"],
    githubLink: "https://github.com/kevincas01/SpaceShipTrainer",
  },
  {
    title: "Tigerfit",
    description: `A full-stack fitness app for Princeton students to track workouts and visualize progress, gaining 100+ active users. Features interactive charts and analytics on weight and lifted weight. Published on TigerApps, Princeton’s student-built app hub.`,
    skills: ["Python", "Flask", "Javascript", "HTML", "CSS"],
  },
];
